services:
  - type: web
    name: backend-krishimitra
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGINS
        value: https://krishimitra2.netlify.app,http://localhost:3000
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0 